### ISSUE TITLE
Selecting an image/file

### ISSUE THREAD

**Issue by cbroberg** [crossfield/react-drafts#32]
Thanks this could be an amazing tool ... 

## What I was trying to do:
Selecting an image inserted in the content area

## Expected behavior:
An image placeholder to obtain visual access to image properties to edit the initial properties

## Actual behavior:
No placeholder. Do you have any directions or code snippets to do this? 

## OS/platform, browser and browser version
Mac OS, Safari@latest

**Comment by florapdx** [comment]
Hi @cbroberg! I'm not sure that I understand your issue, but you should see this when you select an image with your cursor and then hit the photo button in the toolbar:

![screen shot 2017-09-07 at 12 21 58 am](https://user-images.githubusercontent.com/1137259/30151050-c03defba-9362-11e7-851f-432d779a768c.png)

It can be a little fiddly to select images in the editor, so make sure that you're positioning the cursor close to the bottom of the image before you start dragging to select. This is something I definitely intend to spend some time making easier/more amenable to use. Let me know if you have further questions/thoughts.
